import { tagSeeds } from "./catalog";
import type { FieldRule, PlatformSettings, WriterUiSettings } from "./types";

export type FieldDefinition = {
  key: string;
  section: "我的" | "约期" | "亮灯" | "合作";
  label: string;
  defaultRule: FieldRule;
};

const baseFieldDefinitions: FieldDefinition[] = [
  { key: "profile.userName", section: "我的", label: "用户名称（已停用）", defaultRule: { enabled: false, required: false } },
  { key: "profile.brandName", section: "我的", label: "品牌/工作室名称", defaultRule: { enabled: true, required: true } },
  { key: "profile.wechat", section: "我的", label: "微信ID", defaultRule: { enabled: true, required: true } },
  { key: "profile.socialAccount", section: "我的", label: "社交账号（已停用）", defaultRule: { enabled: false, required: false } },
  { key: "profile.logo", section: "我的", label: "品牌标识（已停用）", defaultRule: { enabled: false, required: false } },
  { key: "profile.workImages", section: "我的", label: "至少1张代表图片", defaultRule: { enabled: true, required: true } },
  { key: "profile.intro", section: "我的", label: "品牌或个人介绍", defaultRule: { enabled: true, required: false } },
  { key: "profile.province", section: "我的", label: "当前省份", defaultRule: { enabled: true, required: true } },
  { key: "profile.city", section: "我的", label: "当前城市", defaultRule: { enabled: true, required: true } },
  { key: "schedule.availability", section: "约期", label: "活动计划或近期无计划", defaultRule: { enabled: true, required: true } },
  { key: "lights.boothDescription", section: "亮灯", label: "一句话介绍（30字以内）", defaultRule: { enabled: true, required: false } },
  { key: "lights.selection", section: "亮灯", label: "至少选择1个标签", defaultRule: { enabled: true, required: true } },
  { key: "lights.customTag", section: "亮灯", label: "自定义标签", defaultRule: { enabled: true, required: false } },
  { key: "opportunity.types", section: "合作", label: "至少选择1种合作需求", defaultRule: { enabled: true, required: true } },
];

export const fieldDefinitions: FieldDefinition[] = [
  ...baseFieldDefinitions,
  ...Object.keys(tagSeeds).map((category) => ({
    key: `lights.category.${category}`,
    section: "亮灯" as const,
    label: `${category}分类`,
    defaultRule: { enabled: true, required: false },
  })),
];

export const defaultFieldRules = Object.fromEntries(
  fieldDefinitions.map((item) => [item.key, item.defaultRule]),
) as Record<string, FieldRule>;

export const defaultWriterUiSettings: WriterUiSettings = {
  pageTitle: "生成",
  pageDescription: "TDE会结合你保存的资料、小红书创作结构和平台趋势词库，生成更完整、更像你的文章。",
  freeTitle: "基础生成模式",
  upgradeTitle: "魔法生成模式",
  generateButton: "生成",
  processingButton: "处理中",
  copyButton: "复制全部",
  viewResultButton: "查看文案",
  statusLabels: {
    queued: "已提交生成",
    analyzing: "正在分析代表图片与标签",
    writing: "正在组织标题和正文",
    checking: "正在检查字数与合规",
    retrying: "生成服务繁忙，正在自动重试",
    completed: "文案已生成",
    failed: "生成未完成",
  },
  waitMessage: "通常会在6秒内完成，无需刷新或重复点击。",
  leaveMessage: "你可以离开当前页面，生成结果会自动保存。",
  expiryWarning: "每种模式只保留最新一篇文章，请及时复制使用。",
  tips: [
    "正在结合你的资料与文章结构。",
    "正在从平台趋势词库中选择适合你的表达。",
    "图片主体越清楚，魔法生成越容易看懂重点。",
    "标签越准确，文章越贴近你的作品、风格和客群。",
    "更新活动计划，文章会自然带上见面日期。",
    "资料越真实完整，生成结果越贴近你。",
  ],
  successDialogTitle: "文案已生成",
  successDialogBody: "及时更新资料，提高文案质量。",
  completedNotificationSubject: "文案已生成",
  completedNotificationBody: "你的{模式}文章《{标题}》已经完成，可前往“生成”查看和复制。",
  failedNotificationSubject: "文案生成未完成",
  failedNotificationBody: "你的{模式}文案经过自动重试后仍未完成，本次不扣除额度，可以重新提交。",
};

export const uiTextDefinitions = [
  { key: "header.customer", section: "页头", label: "客服按钮", value: "客服" },
  { key: "header.logout", section: "页头", label: "退出按钮", value: "退出" },
  { key: "header.logoutConfirm", section: "页头", label: "退出确认", value: "确定退出当前账号吗？" },
  { key: "header.contactTitle", section: "页头", label: "客服弹窗标题", value: "联系TDE" },
  { key: "home.inviteLabel", section: "首页", label: "邀请码输入标题", value: "输入邀请码" },
  { key: "home.eyebrow", section: "首页", label: "首页英文小标题", value: "FRESH AIR" },
  { key: "home.invitePlaceholder", section: "首页", label: "邀请码占位文字", value: "4—8 位邀请码" },
  { key: "home.inviteHint", section: "首页", label: "邀请码提示", value: "首次注册输入邀请码，可联系客服申请邀请码。" },
  { key: "home.join", section: "首页", label: "加入入口", value: "加入TDE" },
  { key: "home.login", section: "首页", label: "登录入口", value: "登录更新资料" },
  { key: "home.privateNote", section: "首页", label: "隐私提示", value: "未公开的档案仅供TDE及授权管理员进行合作匹配；注册手机号只会在你另行授权后供已登录消费者主动查看。" },
  { key: "home.visualEyebrow", section: "首页", label: "首页视觉小标题", value: "PRIVATE CREATIVE DOSSIER" },
  { key: "home.visualTitle", section: "首页", label: "首页视觉标题", value: "COCOC" },
  { key: "home.visualDescription", section: "首页", label: "首页视觉说明", value: "让合适的合作，更准确地找到你" },
  { key: "home.writerTitle", section: "首页", label: "生成文章入口标题", value: "生成文章" },
  { key: "home.writerDescription", section: "首页", label: "生成文章入口说明", value: "保存你的资料，生成更像你的小红书文章。" },
  { key: "home.opportunityTitle", section: "首页", label: "寻找合作入口标题", value: "寻找合作" },
  { key: "home.opportunityDescription", section: "首页", label: "寻找合作入口说明", value: "登记合作意向，让TDE为你匹配合适机会。" },
  { key: "home.chooseService", section: "首页", label: "选择服务提示", value: "你想先从哪里开始？" },
  { key: "auth.back", section: "登录注册", label: "返回按钮", value: "返回" },
  { key: "auth.connecting", section: "登录注册", label: "连接中按钮", value: "正在连接" },
  { key: "login.title", section: "登录注册", label: "登录页标题", value: "登录TDE" },
  { key: "login.description", section: "登录注册", label: "登录页说明", value: "登录后查看并更新你的TDE档案，生成工具和通知也都在这里。" },
  { key: "login.button", section: "登录注册", label: "登录按钮", value: "登录" },
  { key: "login.help", section: "登录注册", label: "账号帮助说明", value: "忘记密码或需要修改手机号？" },
  { key: "login.contact", section: "登录注册", label: "联系处理按钮", value: "联系TDE处理" },
  { key: "login.join", section: "登录注册", label: "注册入口", value: "使用邀请码注册" },
  { key: "join.verifyTitle", section: "登录注册", label: "邀请码页标题", value: "先验证邀请码" },
  { key: "join.eyebrow", section: "登录注册", label: "注册页英文小标题", value: "INVITATION ONLY" },
  { key: "join.registerTitle", section: "登录注册", label: "注册页标题", value: "开启注册" },
  { key: "join.description", section: "登录注册", label: "注册页说明", value: "手机号将用于登录和重要邀约联系，请务必填写准确。" },
  { key: "join.inviteHint", section: "登录注册", label: "邀请码提示", value: "首次注册输入邀请码，可联系客服申请邀请码。" },
  { key: "join.inviteLabel", section: "登录注册", label: "邀请码字段", value: "邀请码" },
  { key: "join.verified", section: "登录注册", label: "邀请码验证成功", value: "邀请码已验证" },
  { key: "join.phoneLabel", section: "登录注册", label: "手机号字段", value: "手机号" },
  { key: "join.confirmPhoneLabel", section: "登录注册", label: "确认手机号字段", value: "再次确认手机号" },
  { key: "join.wechatLabel", section: "登录注册", label: "微信ID字段", value: "微信ID" },
  { key: "join.wechatPlaceholder", section: "登录注册", label: "微信ID输入提示", value: "填写可以联系到你的微信ID" },
  { key: "join.provinceLabel", section: "登录注册", label: "注册省份字段", value: "常驻省份" },
  { key: "join.cityLabel", section: "登录注册", label: "注册城市字段", value: "常驻城市" },
  { key: "join.selectProvince", section: "登录注册", label: "注册省份选择提示", value: "请选择省份" },
  { key: "join.selectCity", section: "登录注册", label: "注册城市选择提示", value: "请选择城市" },
  { key: "join.passwordLabel", section: "登录注册", label: "密码字段", value: "密码" },
  { key: "join.confirmPasswordLabel", section: "登录注册", label: "确认密码字段", value: "再次确认密码" },
  { key: "join.defaultPasswordHint", section: "登录注册", label: "默认密码提示", value: "初始密码为注册手机号，可在“我的”修改。" },
  { key: "join.agreement", section: "登录注册", label: "注册协议文字", value: "我已阅读并同意用户协议和隐私政策，提交内容会用于平台匹配、查看、联系及资料下载。" },
  { key: "join.success", section: "登录注册", label: "注册成功提示", value: "注册成功，正在进入你的TDE档案。" },
  { key: "join.welcomeSubject", section: "登录注册", label: "新用户欢迎通知标题", value: "欢迎加入TDE" },
  { key: "join.welcomeBody", section: "登录注册", label: "新用户欢迎通知正文", value: "请先完善你的图片、标签、活动日期、介绍和合作需求。资料越及时，TDE越容易准确理解你。" },
  { key: "join.verifyButton", section: "登录注册", label: "验证邀请码按钮", value: "验证邀请码" },
  { key: "join.registerButton", section: "登录注册", label: "注册按钮", value: "提交注册" },
  { key: "join.login", section: "登录注册", label: "已有账号入口", value: "直接登录" },
  { key: "join.existing", section: "登录注册", label: "已有账号提示", value: "已经注册？" },
  { key: "join.intentTitle", section: "登录注册", label: "注册服务选择标题", value: "你希望TDE帮你做什么？" },
  { key: "join.intentWriter", section: "登录注册", label: "生成文章选项", value: "生成文章" },
  { key: "join.intentOpportunity", section: "登录注册", label: "寻找合作选项", value: "寻找合作" },
  { key: "join.opportunityTitle", section: "登录注册", label: "合作类型标题", value: "你想寻找哪些机会？" },
  { key: "join.opportunityConsent", section: "登录注册", label: "合作联系授权", value: "允许TDE根据我主动提交的资料联系并匹配合作机会。" },
  { key: "opportunity.eyebrow", section: "合作机会", label: "合作页英文小标题", value: "COCOC OPPORTUNITIES" },
  { key: "opportunity.title", section: "合作机会", label: "合作页标题", value: "让合适的合作找到你" },
  { key: "opportunity.description", section: "合作机会", label: "合作页说明", value: "选择你想寻找的机会。TDE会结合你的城市、活动日期、标签和介绍进行人工匹配。" },
  { key: "opportunity.typesTitle", section: "合作机会", label: "合作类型标题", value: "我想寻找" },
  { key: "opportunity.consent", section: "合作机会", label: "合作授权文字", value: "允许TDE根据我主动提交的资料联系并匹配合作机会。" },
  { key: "opportunity.save", section: "合作机会", label: "保存合作意向按钮", value: "保存合作意向" },
  { key: "opportunity.saved", section: "合作机会", label: "保存成功提示", value: "合作意向已保存" },
  { key: "studio.reload", section: "工作台", label: "重新加载按钮", value: "重新加载" },
  { key: "studio.loading", section: "工作台", label: "工作台加载提示", value: "正在连接你的TDE档案" },
  { key: "studio.loadError", section: "工作台", label: "工作台加载失败提示", value: "创作档案暂时无法打开" },
  { key: "studio.incompleteName", section: "工作台", label: "未填写名称提示", value: "待完善资料" },
  { key: "studio.completeness", section: "工作台", label: "资料完整度提示", value: "资料完整度 {完整度}%" },
  { key: "dossier.eyebrow", section: "档案", label: "档案页英文小标题", value: "MY COCOC DOSSIER" },
  { key: "dossier.title", section: "档案", label: "档案页标题", value: "我的TDE档案" },
  { key: "dossier.description", section: "档案", label: "档案页说明", value: "资料越及时，TDE越容易准确理解你和你的合作方向。" },
  { key: "dossier.updateButton", section: "档案", label: "更新档案按钮", value: "更新我的档案" },
  { key: "dossier.updatedAt", section: "档案", label: "最近更新时间", value: "最近更新：{时间}" },
  { key: "dossier.identityTitle", section: "档案", label: "身份状态标题", value: "你在做什么" },
  { key: "dossier.identityEmpty", section: "档案", label: "身份未填写提示", value: "还没有填写名称和标签" },
  { key: "dossier.scheduleTitle", section: "档案", label: "日期状态标题", value: "近期活动日期" },
  { key: "dossier.scheduleEmpty", section: "档案", label: "日期未填写提示", value: "还没有更新活动日期" },
  { key: "dossier.scheduleNone", section: "档案", label: "近期无计划提示", value: "近期无计划" },
  { key: "dossier.scheduleExpired", section: "档案", label: "日期过期提示", value: "活动计划已过期，请更新" },
  { key: "dossier.scheduleFuture", section: "档案", label: "下一场活动提示", value: "下一场：{日期}" },
  { key: "dossier.opportunityTitle", section: "档案", label: "合作状态标题", value: "期待哪些合作" },
  { key: "dossier.opportunityEmpty", section: "档案", label: "合作未填写提示", value: "还没有选择合作需求" },
  { key: "dossier.cityEmpty", section: "档案", label: "城市未填写提示", value: "城市未填写" },
  { key: "dossier.tagsEmpty", section: "档案", label: "标签未填写提示", value: "还没有选择标签" },
  { key: "dossier.matchingEnabled", section: "档案", label: "合作匹配开启提示", value: "TDE可以根据你的资料联系你" },
  { key: "dossier.matchingDisabled", section: "档案", label: "合作匹配未开启提示", value: "尚未开启合作匹配" },
  { key: "dossier.emptyValue", section: "档案", label: "普通未填写提示", value: "未填写" },
  { key: "dossier.optionalEmpty", section: "档案", label: "选填未填写提示", value: "选填，暂未填写" },
  { key: "dossier.privateNote", section: "档案", label: "档案隐私提示", value: "这份档案不会在前台公开。TDE及获得授权的管理员会用它进行资源整理和合作匹配。" },
  { key: "dossier.completenessLabel", section: "档案", label: "档案完成度标签", value: "档案完成度" },
  { key: "dossier.recordTitle", section: "档案", label: "档案内容标题", value: "档案内容" },
  { key: "dossier.recordDescription", section: "档案", label: "档案内容说明", value: "这些信息只用于TDE内部整理、联系和匹配。" },
  { key: "profile.submit", section: "工作台", label: "我的提交按钮", value: "保存更新" },
  { key: "profile.eyebrow", section: "工作台", label: "我的页英文小标题", value: "PROFILE" },
  { key: "profile.title", section: "工作台", label: "我的页标题", value: "我的资料" },
  { key: "profile.description", section: "工作台", label: "我的页说明", value: "管理账号、通知和邀请码。创作资料可在“更新”中随时补充。" },
  { key: "profile.phoneLabel", section: "我的", label: "手机号标题", value: "注册手机号" },
  { key: "profile.brandLabel", section: "我的", label: "品牌名称字段", value: "品牌/工作室名称" },
  { key: "profile.wechatLabel", section: "我的", label: "微信ID字段", value: "微信ID" },
  { key: "profile.accountSave", section: "我的", label: "保存账号资料按钮", value: "保存名称" },
  { key: "profile.accountSaved", section: "我的", label: "账号资料保存成功提示", value: "账号资料已保存" },
  { key: "profile.accountTitle", section: "我的", label: "账号信息标题", value: "账号信息" },
  { key: "profile.passwordTitle", section: "我的", label: "修改密码标题", value: "修改密码" },
  { key: "profile.currentPassword", section: "我的", label: "当前密码字段", value: "当前密码" },
  { key: "profile.newPassword", section: "我的", label: "新密码字段", value: "新密码" },
  { key: "profile.confirmPassword", section: "我的", label: "确认新密码字段", value: "再次输入新密码" },
  { key: "profile.passwordButton", section: "我的", label: "修改密码按钮", value: "确认修改密码" },
  { key: "profile.passwordSaved", section: "我的", label: "密码修改成功提示", value: "密码已修改" },
  { key: "profile.notificationsTitle", section: "我的", label: "通知入口标题", value: "通知" },
  { key: "profile.notificationsDescription", section: "我的", label: "通知入口说明", value: "平台邀约、复核结果和系统消息。" },
  { key: "profile.notificationsButton", section: "我的", label: "查看通知按钮", value: "查看通知" },
  { key: "profile.notificationsUnread", section: "我的", label: "未读数量提示", value: "{数量} 条未读" },
  { key: "profile.notificationsEmpty", section: "我的", label: "无未读提示", value: "暂无未读通知" },
  { key: "invite.rewardSubject", section: "我的", label: "邀请成功通知标题", value: "邀请成功，生成额度已增加" },
  { key: "invite.rewardBody", section: "我的", label: "邀请成功通知正文", value: "有一位新用户使用你的邀请码完成注册。基础生成和魔法生成额度已各增加2次。" },
  { key: "profile.backToMain", section: "我的", label: "返回我的按钮", value: "返回我的" },
  { key: "invite.copySuccess", section: "我的", label: "邀请信息复制成功提示", value: "邀请信息已复制" },
  { key: "invite.copyFailed", section: "我的", label: "邀请信息复制失败提示", value: "复制失败，请稍后重试" },
  { key: "inbox.eyebrow", section: "我的", label: "通知页英文小标题", value: "NOTIFICATIONS" },
  { key: "inbox.title", section: "我的", label: "通知页标题", value: "平台通知" },
  { key: "inbox.description", section: "我的", label: "通知页说明", value: "平台邀约、标签复核结果和系统消息会出现在这里。" },
  { key: "inbox.kindInvitation", section: "我的", label: "邀约通知类型", value: "平台邀约" },
  { key: "inbox.kindReview", section: "我的", label: "复核通知类型", value: "标签复核" },
  { key: "inbox.kindDefault", section: "我的", label: "普通通知类型", value: "平台通知" },
  { key: "inbox.empty", section: "我的", label: "通知空状态", value: "暂时没有通知。" },
  { key: "inbox.dialogEyebrow", section: "我的", label: "通知详情英文小标题", value: "MESSAGE" },
  { key: "profile.updateTitle", section: "更新", label: "更新资料标题", value: "更新" },
  { key: "profile.updateDescription", section: "更新", label: "更新资料说明", value: "更新基本信息、图片、标签、活动日期、合作需求和个人介绍，让TDE更懂你。" },
  { key: "profile.updateButton", section: "更新", label: "进入更新按钮", value: "更新资料" },
  { key: "profile.saveUpdate", section: "更新", label: "保存更新按钮", value: "保存更新" },
  { key: "profile.savedUpdate", section: "更新", label: "保存完成状态", value: "已保存更新" },
  { key: "profile.writeAgainTitle", section: "更新", label: "保存后弹窗标题", value: "再写一篇" },
  { key: "profile.writeAgainYes", section: "更新", label: "保存后确认按钮", value: "好的" },
  { key: "profile.writeAgainLater", section: "更新", label: "保存后稍后按钮", value: "下次吧" },
  { key: "writer.stepProfile", section: "更新", label: "基本信息步骤", value: "基本信息" },
  { key: "writer.stepOpportunity", section: "更新", label: "合作需求步骤", value: "合作需求" },
  { key: "writer.profileTitle", section: "更新", label: "基本信息弹层标题", value: "更新基本信息" },
  { key: "writer.profileDescription", section: "更新", label: "基本信息弹层说明", value: "保持名称、微信ID和常驻城市准确，方便TDE联系和匹配。" },
  { key: "writer.profileSubmit", section: "更新", label: "基本信息保存按钮", value: "保存基本信息" },
  { key: "schedule.eyebrow", section: "工作台", label: "约期页英文小标题", value: "AVAILABILITY" },
  { key: "schedule.planLegend", section: "活动计划", label: "日历已选日期图例", value: "活动计划" },
  { key: "schedule.todayLegend", section: "活动计划", label: "日历今天图例", value: "今天" },
  { key: "schedule.calendarHint", section: "活动计划", label: "日历操作提示", value: "点击日期可添加或取消" },
  { key: "schedule.noPlanTitle", section: "活动计划", label: "近期无计划选项", value: "近期无计划" },
  { key: "schedule.noPlanDescription", section: "活动计划", label: "近期无计划说明", value: "近期没有准备公开的活动计划。" },
  { key: "schedule.markedTitle", section: "活动计划", label: "已选日期标题", value: "已标记活动计划" },
  { key: "schedule.periodFallback", section: "活动计划", label: "活动计划默认名称", value: "线下见面计划" },
  { key: "schedule.syncedSuffix", section: "活动计划", label: "平台同步标记", value: "平台同步" },
  { key: "schedule.empty", section: "活动计划", label: "未选日期提示", value: "还没有标记活动日期。" },
  { key: "schedule.disabled", section: "活动计划", label: "活动计划停用提示", value: "平台当前未收集活动计划，提交后即可继续。" },
  { key: "schedule.savedToast", section: "活动计划", label: "活动计划提交成功提示", value: "活动计划已提交" },
  { key: "schedule.changedToast", section: "活动计划", label: "活动日期更新提示", value: "活动日期已更新，请提交确认" },
  { key: "schedule.lockedDate", section: "活动计划", label: "同步日期不可删除提示", value: "该日期由平台活动同步，不能在这里删除" },
  { key: "schedule.deleteLabel", section: "活动计划", label: "删除日期按钮名称", value: "删除活动日期" },
  { key: "schedule.staleTitle", section: "活动计划", label: "30天确认标题", value: "确认你的活动计划" },
  { key: "schedule.staleDescription", section: "活动计划", label: "30天确认说明", value: "距离上次确认已超过30天，请确认当前活动计划仍然有效。" },
  { key: "schedule.staleCount", section: "活动计划", label: "30天确认数量", value: "{数量} 条活动计划" },
  { key: "schedule.staleEmpty", section: "活动计划", label: "30天确认无计划提示", value: "当前为近期无计划" },
  { key: "schedule.generateEyebrow", section: "活动计划", label: "生成前确认英文小标题", value: "BEFORE GENERATING" },
  { key: "schedule.generateTitle", section: "活动计划", label: "生成前确认标题", value: "确认这次要写入的活动计划" },
  { key: "schedule.generateDescription", section: "活动计划", label: "生成前确认说明", value: "日期会自然写进文章，方便读者知道何时能在线下见到你。" },
  { key: "schedule.generateMissing", section: "活动计划", label: "没有未来计划提示", value: "近期有公开活动吗？更新后，文章会自动带上见面日期。" },
  { key: "schedule.generateExpired", section: "活动计划", label: "计划过期提示", value: "你的活动计划已过期，更新日期，让文章保持新鲜。" },
  { key: "schedule.generateFuture", section: "活动计划", label: "已有未来计划提示", value: "下一场见面：{日期}" },
  { key: "schedule.generateNoPlan", section: "活动计划", label: "近期无计划提示", value: "近期无计划，生成文章时不会加入日期。" },
  { key: "schedule.generateFill", section: "活动计划", label: "填写计划按钮", value: "填写活动计划" },
  { key: "schedule.generateUpdate", section: "活动计划", label: "更新日期按钮", value: "更新日期" },
  { key: "schedule.generateConfirm", section: "活动计划", label: "确认并生成按钮", value: "确认并生成" },
  { key: "schedule.generateConfirming", section: "活动计划", label: "确认中状态", value: "确认中" },
  { key: "schedule.generateModify", section: "活动计划", label: "修改计划按钮", value: "修改计划" },
  { key: "schedule.generateCancel", section: "活动计划", label: "取消生成按钮", value: "取消" },
  { key: "lights.eyebrow", section: "工作台", label: "亮灯页英文小标题", value: "ALL TAGS" },
  { key: "lights.title", section: "工作台", label: "亮灯页标题", value: "亮灯" },
  { key: "lights.quickPrompt", section: "工作台", label: "展位描述引导", value: "哪个词能准确描述你的展位，试着写一下（30个字以内）" },
  { key: "lights.quickPlaceholder", section: "工作台", label: "展位描述输入提示", value: "例如：原创陶瓷与现场手作体验" },
  { key: "lights.quickSubmit", section: "工作台", label: "展位描述提交按钮", value: "提交" },
  { key: "lights.quickSkip", section: "工作台", label: "展位描述跳过按钮", value: "跳过" },
  { key: "lights.remembered", section: "工作台", label: "描述提交成功引导", value: "TDE已经记住你，请继续亮灯" },
  { key: "lights.quickContinue", section: "工作台", label: "描述成功继续按钮", value: "继续亮灯" },
  { key: "lights.quickEdit", section: "工作台", label: "修改展位描述按钮", value: "修改描述" },
  { key: "lights.moreTitle", section: "工作台", label: "分类页说明标题", value: "点亮适合你的标签" },
  { key: "lights.recommended", section: "工作台", label: "自动匹配标签标记", value: "TDE推荐" },
  { key: "lights.previous", section: "工作台", label: "分类上一步按钮", value: "上一步" },
  { key: "lights.next", section: "工作台", label: "分类继续按钮", value: "继续" },
  { key: "lights.customOpen", section: "工作台", label: "自定义标签入口", value: "没有合适的？新增标签" },
  { key: "lights.customPlaceholder", section: "工作台", label: "自定义标签输入提示", value: "7个字以内" },
  { key: "lights.customSubmit", section: "工作台", label: "自定义标签提交按钮", value: "新增" },
  { key: "writer.eyebrow", section: "工作台", label: "生成文章页英文小标题", value: "COCOC WRITER" },
  { key: "writer.setupTitle", section: "生成文章", label: "资料步骤标题", value: "生成前，按顺序完成" },
  { key: "writer.setupDescription", section: "生成文章", label: "资料步骤说明", value: "完成上一项后，下一项会自动开放。" },
  { key: "writer.setupEyebrow", section: "生成文章", label: "资料步骤英文小标题", value: "WORKFLOW" },
  { key: "writer.panelEyebrow", section: "生成文章", label: "资料弹层英文小标题", value: "ARTICLE SETUP" },
  { key: "writer.mobileEdit", section: "生成文章", label: "手机编辑切换", value: "编辑" },
  { key: "writer.mobilePreview", section: "生成文章", label: "手机预览切换", value: "预览" },
  { key: "writer.stepImage", section: "生成文章", label: "图片步骤", value: "上传图片" },
  { key: "writer.stepBoothDescription", section: "生成文章", label: "一句话介绍步骤", value: "一句话介绍" },
  { key: "writer.stepTags", section: "生成文章", label: "标签步骤", value: "告诉TDE你是谁" },
  { key: "writer.stepSchedule", section: "生成文章", label: "活动计划步骤", value: "活动计划" },
  { key: "writer.stepCity", section: "生成文章", label: "城市步骤", value: "常驻城市" },
  { key: "writer.stepIntro", section: "生成文章", label: "介绍步骤", value: "介绍你和你的作品" },
  { key: "writer.stepComplete", section: "生成文章", label: "步骤已完成", value: "已完成" },
  { key: "writer.stepPending", section: "生成文章", label: "步骤待完成", value: "待完成" },
  { key: "writer.stepOptional", section: "生成文章", label: "步骤选填状态", value: "选填" },
  { key: "writer.stepLocked", section: "生成文章", label: "步骤未开放", value: "请先完成上一项" },
  { key: "writer.backToResults", section: "生成文章", label: "返回文章按钮", value: "返回文章" },
  { key: "writer.editComplete", section: "生成文章", label: "资料更新完成按钮", value: "更新完毕，开始生成" },
  { key: "writer.closePanel", section: "生成文章", label: "关闭资料弹层", value: "关闭" },
  { key: "writer.imageTitle", section: "生成文章", label: "图片弹层标题", value: "上传这次要写的图片" },
  { key: "writer.imageDescription", section: "生成文章", label: "图片弹层说明", value: "选择一张最重要的图片，裁切确认后用于文章分析。原图最大20MB。" },
  { key: "writer.imageChoose", section: "生成文章", label: "选择图片按钮", value: "选择图片" },
  { key: "writer.imageReplace", section: "生成文章", label: "更换图片按钮", value: "重新选择" },
  { key: "writer.imageContinue", section: "生成文章", label: "图片继续按钮", value: "继续筛选标签" },
  { key: "writer.imageFormat", section: "生成文章", label: "图片格式提示", value: "JPG、PNG、WebP，最大20MB" },
  { key: "writer.imageSaved", section: "生成文章", label: "图片保存成功提示", value: "代表图片已保存" },
  { key: "writer.imagePreview", section: "生成文章", label: "图片预览提示", value: "最终使用图片" },
  { key: "writer.boothDescriptionTitle", section: "生成文章", label: "一句话介绍弹层标题", value: "一句话介绍" },
  { key: "writer.boothDescriptionDescription", section: "生成文章", label: "一句话介绍弹层说明", value: "选填。用一句话说清你是谁、做什么，帮助TDE更快理解你。最多30个字。" },
  { key: "writer.boothDescriptionPlaceholder", section: "生成文章", label: "一句话介绍输入提示", value: "例如：原创陶艺与现场手作体验" },
  { key: "writer.boothDescriptionSubmit", section: "生成文章", label: "一句话介绍保存按钮", value: "保存一句话介绍" },
  { key: "writer.cropTitle", section: "生成文章", label: "裁切标题", value: "调整图片范围" },
  { key: "writer.cropDescription", section: "生成文章", label: "裁切说明", value: "拖动图片并调整大小，确认最终使用区域。" },
  { key: "writer.cropZoom", section: "生成文章", label: "裁切缩放", value: "缩放" },
  { key: "writer.cropReset", section: "生成文章", label: "裁切重置", value: "重置" },
  { key: "writer.cropConfirm", section: "生成文章", label: "裁切确认", value: "确认保存" },
  { key: "writer.tagsTitle", section: "生成文章", label: "标签弹层标题", value: "告诉TDE你是谁" },
  { key: "writer.tagsDescription", section: "生成文章", label: "标签弹层说明", value: "按分类选择长期标签，每个分类最多选择8个。" },
  { key: "writer.customTagEyebrow", section: "生成文章", label: "新增标签英文小标题", value: "CUSTOM TAG" },
  { key: "writer.customTagTitle", section: "生成文章", label: "新增标签标题", value: "新增你的专属标签" },
  { key: "writer.customTagDescription", section: "生成文章", label: "新增标签说明", value: "没有合适的标签时，可以直接新增并提交平台复核。" },
  { key: "writer.tagsSubmit", section: "生成文章", label: "标签提交按钮", value: "保存并继续" },
  { key: "writer.scheduleSubmit", section: "生成文章", label: "活动计划提交按钮", value: "保存并继续" },
  { key: "writer.cityTitle", section: "生成文章", label: "城市弹层标题", value: "常驻城市" },
  { key: "writer.cityDescription", section: "生成文章", label: "城市弹层说明", value: "选择你目前常驻的省份和城市。" },
  { key: "writer.cityProvince", section: "生成文章", label: "省份字段", value: "省份" },
  { key: "writer.cityCity", section: "生成文章", label: "城市字段", value: "城市" },
  { key: "writer.selectProvince", section: "生成文章", label: "省份选择提示", value: "请选择省份" },
  { key: "writer.selectCity", section: "生成文章", label: "城市选择提示", value: "请选择城市" },
  { key: "writer.citySubmit", section: "生成文章", label: "城市提交按钮", value: "保存并继续" },
  { key: "writer.introTitle", section: "生成文章", label: "介绍弹层标题", value: "介绍你和你的作品" },
  { key: "writer.introDescription", section: "生成文章", label: "介绍弹层说明", value: "选填。可介绍你的创作、作品、风格和适合的合作场景。" },
  { key: "writer.introSubmit", section: "生成文章", label: "介绍提交按钮", value: "更新完毕，开始生成" },
  { key: "writer.resultFree", section: "生成文章", label: "普通结果切换", value: "普通文章" },
  { key: "writer.resultUpgrade", section: "生成文章", label: "加强结果切换", value: "加强文章" },
  { key: "writer.emptyTitle", section: "生成文章", label: "无结果标题", value: "还没有生成文章" },
  { key: "writer.emptyDescription", section: "生成文章", label: "无结果说明", value: "先按右侧顺序完善资料，再选择普通生成或加强生成。" },
  { key: "writer.newArticle", section: "生成文章", label: "生成新文章入口", value: "点击生成新文章" },
  { key: "writer.newGenerate", section: "生成文章", label: "新生成按钮", value: "新生成" },
  { key: "writer.generateAgain", section: "生成文章", label: "再次生成按钮", value: "换一种写法" },
  { key: "writer.updateMaterials", section: "生成文章", label: "更新资料按钮", value: "让TDE更懂你" },
  { key: "writer.updateHint", section: "生成文章", label: "更新资料提示", value: "资料越真实，文章越像你" },
  { key: "writer.readyToGenerate", section: "生成文章", label: "资料可生成提示", value: "TDE已经记住这些资料" },
  { key: "writer.copySuccess", section: "生成文章", label: "复制成功提示", value: "标题和正文已复制" },
  { key: "writer.copyFailed", section: "生成文章", label: "复制失败提示", value: "复制失败，请稍后重试" },
  { key: "writer.uploadFailed", section: "生成文章", label: "图片上传失败提示", value: "图片上传失败，请稍后重试" },
  { key: "writer.saveUpdateFailed", section: "生成文章", label: "资料保存失败提示", value: "资料保存失败，请稍后重试" },
  { key: "writer.generateFailed", section: "生成文章", label: "文章生成失败提示", value: "文章生成失败，请稍后重试" },
  { key: "writer.remaining", section: "生成文章", label: "剩余额度文字", value: "剩余 {次数} 次" },
  { key: "writer.saving", section: "生成文章", label: "保存中状态", value: "保存中" },
  { key: "lights.pendingReview", section: "生成文章", label: "标签待复核标记", value: "待复核" },
  { key: "schedule.submit", section: "工作台", label: "约期提交按钮", value: "提交并进入亮灯" },
  { key: "lights.add", section: "工作台", label: "新增标签按钮", value: "新增" },
  { key: "lights.save", section: "工作台", label: "保存标签按钮", value: "保存标签更新" },
  { key: "lights.submit", section: "工作台", label: "完成亮灯按钮", value: "确认标签并完成亮灯" },
  { key: "lights.continue", section: "工作台", label: "继续完善标签", value: "继续完善标签" },
  { key: "lights.writer", section: "工作台", label: "前往智能体按钮", value: "去生成文案" },
  { key: "writer.contactTitle", section: "工作台", label: "额度不足标题", value: "请联系客服申请使用额度。" },
  { key: "writer.acknowledge", section: "工作台", label: "额度弹窗关闭按钮", value: "知道了" },
  { key: "schedule.confirmButton", section: "工作台", label: "30天确认按钮", value: "仍然有效，继续使用" },
  { key: "writer.guideTitle", section: "创作标准弹窗", label: "弹窗标题", value: "小红书好文章的4个标准" },
  { key: "writer.guideEyebrow", section: "创作标准弹窗", label: "弹窗英文小标题", value: "COCOC CREATION SYSTEM" },
  { key: "writer.guideLead", section: "创作标准弹窗", label: "弹窗引导", value: "普通 AI 也能写，但一篇更好用的文章还需要同时照顾下面四件事。" },
  { key: "writer.guideItem1Title", section: "创作标准弹窗", label: "标准一标题", value: "有人点开" },
  { key: "writer.guideItem1Body", section: "创作标准弹窗", label: "标准一说明", value: "标题说清对象、内容和看点。" },
  { key: "writer.guideItem2Title", section: "创作标准弹窗", label: "标准二标题", value: "有人看完" },
  { key: "writer.guideItem2Body", section: "创作标准弹窗", label: "标准二说明", value: "正文有真实细节、清晰结构和阅读节奏。" },
  { key: "writer.guideItem3Title", section: "创作标准弹窗", label: "标准三标题", value: "有人相信" },
  { key: "writer.guideItem3Body", section: "创作标准弹窗", label: "标准三说明", value: "表达来自你的作品、经历和活动计划。" },
  { key: "writer.guideItem4Title", section: "创作标准弹窗", label: "标准四标题", value: "平台知道推荐给谁" },
  { key: "writer.guideItem4Body", section: "创作标准弹窗", label: "标准四说明", value: "趋势词、作品标签、风格和客群保持一致。" },
  { key: "writer.guideClosing", section: "创作标准弹窗", label: "弹窗结尾", value: "TDE会结合你的图片、介绍、标签和活动计划，再匹配平台维护的趋势词库与小红书创作结构，帮你写成一篇更完整、更像你的文章。" },
  { key: "writer.guideDisclaimer", section: "创作标准弹窗", label: "弹窗说明", value: "TDE不承诺爆文。资料越真实完整，生成结果越贴近你。" },
  { key: "writer.guideClose", section: "创作标准弹窗", label: "收起按钮", value: "我知道了" },
  { key: "writer.guideReopen", section: "创作标准弹窗", label: "小灯入口提示", value: "为什么要用TDE" },
] as const;

export const defaultUiText = Object.fromEntries(
  uiTextDefinitions.map((item) => [item.key, item.value]),
) as Record<string, string>;

export const defaultPlatformSettings: PlatformSettings = {
  productName: "TDE",
  headline: "让TDE在合适的时候想到你",
  subheadline:
    "告诉我们你在做什么、在哪里、近期有什么安排。遇到合适的市集、快闪、空间、品牌和活动合作时，TDE可以更准确地联系你。",
  contactText: "联系TDE\n官方微信：aaabht\n小红书：12345",
  profileExample:
    "例如：独立手作品牌，专注天然材料首饰，适合市集、快闪和线下体验活动。",
  scheduleTitle: "更新线下活动日期匹配热搜词",
  scheduleDescription: "有公开活动时，日期会自然写进文章，也能帮助平台匹配活动；近期无计划则不会加入日期。",
  lightsDescription: "选出最像你的标签，帮助TDE理解你的作品、风格和客群；每个分类最多选择8个。",
  writerUi: defaultWriterUiSettings,
  writerIntro: { enabled: true, version: "1" },
  uiText: defaultUiText,
  homeShowcase: {
    enabled: false,
    cards: [
      { enabled: true, index: "01", category: "城市生活", eyebrow: "SELECTED EVENT", title: "城市周末市集", footer: "只在匹配时出现", background: "#E5B93F", foreground: "#111111", imageUrl: null },
      { enabled: true, index: "02", category: "艺术设计", eyebrow: "SELECTED EVENT", title: "青年艺术节", footer: "只在匹配时出现", background: "#5378A8", foreground: "#FFFFFF", imageUrl: null },
      { enabled: true, index: "03", category: "品牌活动", eyebrow: "SELECTED EVENT", title: "品牌快闪店", footer: "只在匹配时出现", background: "#555B63", foreground: "#FFFFFF", imageUrl: null },
    ],
  },
  homeCriteria: [
    { id: "city", label: "你在做什么", icon: "Lightbulb", enabled: true, sortOrder: 1 },
    { id: "schedule", label: "近期活动日期", icon: "Lightbulb", enabled: true, sortOrder: 2 },
    { id: "tags", label: "期待哪些合作", icon: "Lightbulb", enabled: true, sortOrder: 3 },
  ],
  inviteSharing: {
    heading: "邀请朋友，一起获得生成额度",
    description: "好友使用你的邀请码注册成功后，基础生成和魔法生成额度各增加2次。邀请码可重复使用。",
    buttonText: "复制邀请信息",
    buttonIcon: "Clipboard",
    template: "我在用TDE，邀请你同在。\n\n它会记住你的作品、标签和活动计划，少写提示词，更快生成像你的小红书文章。\n\n专属邀请码：{邀请码}\n加入TDE：{加入网址}",
    joinUrl: "https://thedesignexpo.org.cn/join",
  },
  inviteContactText: "联系TDE 微信 TheDesignExpo_Official 获得邀请码",
  sms: {
    enabled: false,
    signName: "TDE",
    verificationTemplateCode: "",
    notificationTypes: [
      { key: "invitation", label: "平台点名邀约", enabled: true, smsEnabled: true, templateCode: "", linkPath: "/studio?section=profile&view=inbox", sortOrder: 1 },
      { key: "activity", label: "活动通知", enabled: true, smsEnabled: true, templateCode: "", linkPath: "/studio?section=profile&view=inbox", sortOrder: 2 },
      { key: "activity_change", label: "活动变更", enabled: true, smsEnabled: true, templateCode: "", linkPath: "/studio?section=profile&view=inbox", sortOrder: 3 },
      { key: "profile", label: "资料补充", enabled: true, smsEnabled: false, templateCode: "", linkPath: "/studio?section=profile", sortOrder: 4 },
      { key: "tag_review", label: "标签审核", enabled: true, smsEnabled: false, templateCode: "", linkPath: "/studio?section=profile&view=inbox", sortOrder: 5 },
      { key: "schedule", label: "档期确认", enabled: true, smsEnabled: false, templateCode: "", linkPath: "/studio?section=schedule", sortOrder: 6 },
      { key: "copy_complete", label: "文案生成完成", enabled: true, smsEnabled: false, templateCode: "", linkPath: "/studio?section=writer", sortOrder: 7 },
      { key: "security", label: "账号安全", enabled: true, smsEnabled: true, templateCode: "", linkPath: "/login", sortOrder: 8 },
      { key: "system", label: "系统公告", enabled: true, smsEnabled: false, templateCode: "", linkPath: "/studio?section=profile&view=inbox", sortOrder: 9 },
    ],
  },
  navigation: {
    dossier: "档案",
    profile: "我的",
    writer: "生成",
    update: "更新",
  },
  navigationIcons: {
    dossier: "FileText",
    profile: "UserRound",
    writer: "Sparkles",
    update: "FileText",
  },
  fieldRules: defaultFieldRules,
};

export const settingLimits: Record<keyof PlatformSettings, number> = {
  productName: 30,
  headline: 80,
  subheadline: 180,
  contactText: 300,
  profileExample: 200,
  scheduleTitle: 60,
  scheduleDescription: 160,
  lightsDescription: 160,
  writerUi: 0,
  writerIntro: 0,
  uiText: 0,
  homeShowcase: 0,
  homeCriteria: 0,
  inviteSharing: 0,
  inviteContactText: 160,
  sms: 0,
  navigation: 0,
  navigationIcons: 0,
  fieldRules: 0,
};

export const allowedNavigationIcons = [
  "Compass",
  "Tags",
  "CalendarDays",
  "Bell",
  "UserRound",
  "MapPin",
  "Sparkles",
  "FileText",
  "Lightbulb",
  "Handshake",
] as const;

export const allowedContentIcons = [
  "MapPin",
  "CalendarDays",
  "Tags",
  "Compass",
  "Sparkles",
  "Users",
  "Clipboard",
  "Copy",
  "Send",
  "Lightbulb",
] as const;
